{{- if .Values.gatewayApi.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "gyre.fullname" . }}
  labels:
    {{- include "gyre.labels" . | nindent 4 }}
  {{- with .Values.gatewayApi.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.gatewayApi.parentRefs }}
  parentRefs:
    {{- toYaml .Values.gatewayApi.parentRefs | nindent 4 }}
  {{- end }}
  {{- if .Values.gatewayApi.hostnames }}
  hostnames:
    {{- toYaml .Values.gatewayApi.hostnames | nindent 4 }}
  {{- end }}
  rules:
    {{- if .Values.gatewayApi.rules }}
    {{- toYaml .Values.gatewayApi.rules | nindent 4 }}
    {{- else }}
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "gyre.fullname" . }}
          port: {{ .Values.service.port }}
    {{- end }}
{{- end }}
