{{- if .Values.admin.autoGenerate -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.admin.secretName }}
  labels:
    {{- include "gyre.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
    gyre.io/secret-type: initial-admin-password
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  password: {{ randAlphaNum 24 | quote }}
{{- end }}
